name: build
env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

on:
  workflow_dispatch:
  pull_request:
  push:
    paths-ignore:
      - "README.md"
      - ".gitignore"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Gradle Build and Test
        run: |
          ./gradlew build test --info --stacktrace
