name: Development build - Linux

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited]
  push:
    # paths-ignore:
    #   - ".github/**"
    #   - "README.md"
    #   - ".gitignore"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Gradle Build
        run: |
          ./gradlew build
